QT += core
QT -= gui

TARGET = SenseServer
CONFIG += console
CONFIG -= app_bundle

MOC_DIR = build\moc
OBJECTS_DIR = build\obj
DESTDIR = bin

INCLUDEPATH += \
    thirdparty/live/BasicUsageEnvironment/include \
    thirdparty/live/groupsock/include \
    thirdparty/live/liveMedia/include \
    thirdparty/live/UsageEnvironment/include

QMAKE_CXXFLAGS += -O2 -DSOCKLEN_T=socklen_t -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -Wall -DBSD=1

TEMPLATE = app

SOURCES += \
    thirdparty/live/BasicUsageEnvironment/BasicHashTable.cpp \
    thirdparty/live/BasicUsageEnvironment/BasicTaskScheduler.cpp \
    thirdparty/live/BasicUsageEnvironment/BasicTaskScheduler0.cpp \
    thirdparty/live/BasicUsageEnvironment/BasicUsageEnvironment.cpp \
    thirdparty/live/BasicUsageEnvironment/BasicUsageEnvironment0.cpp \
    thirdparty/live/BasicUsageEnvironment/DelayQueue.cpp \
    thirdparty/live/groupsock/GroupEId.cpp \
    thirdparty/live/groupsock/Groupsock.cpp \
    thirdparty/live/groupsock/GroupsockHelper.cpp \
    thirdparty/live/groupsock/IOHandlers.cpp \
    thirdparty/live/groupsock/NetAddress.cpp \
    thirdparty/live/groupsock/NetInterface.cpp \
    thirdparty/live/liveMedia/AC3AudioFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/AC3AudioRTPSink.cpp \
    thirdparty/live/liveMedia/AC3AudioRTPSource.cpp \
    thirdparty/live/liveMedia/AC3AudioStreamFramer.cpp \
    thirdparty/live/liveMedia/ADTSAudioFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/ADTSAudioFileSource.cpp \
    thirdparty/live/liveMedia/AMRAudioFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/AMRAudioFileSink.cpp \
    thirdparty/live/liveMedia/AMRAudioFileSource.cpp \
    thirdparty/live/liveMedia/AMRAudioRTPSink.cpp \
    thirdparty/live/liveMedia/AMRAudioRTPSource.cpp \
    thirdparty/live/liveMedia/AMRAudioSource.cpp \
    thirdparty/live/liveMedia/AudioInputDevice.cpp \
    thirdparty/live/liveMedia/AudioRTPSink.cpp \
    thirdparty/live/liveMedia/AVIFileSink.cpp \
    thirdparty/live/liveMedia/Base64.cpp \
    thirdparty/live/liveMedia/BasicUDPSink.cpp \
    thirdparty/live/liveMedia/BasicUDPSource.cpp \
    thirdparty/live/liveMedia/BitVector.cpp \
    thirdparty/live/liveMedia/ByteStreamFileSource.cpp \
    thirdparty/live/liveMedia/ByteStreamMemoryBufferSource.cpp \
    thirdparty/live/liveMedia/ByteStreamMultiFileSource.cpp \
    thirdparty/live/liveMedia/DeviceSource.cpp \
    thirdparty/live/liveMedia/DigestAuthentication.cpp \
    thirdparty/live/liveMedia/DVVideoFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/DVVideoRTPSink.cpp \
    thirdparty/live/liveMedia/DVVideoRTPSource.cpp \
    thirdparty/live/liveMedia/DVVideoStreamFramer.cpp \
    thirdparty/live/liveMedia/EBMLNumber.cpp \
    thirdparty/live/liveMedia/FileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/FileSink.cpp \
    thirdparty/live/liveMedia/FramedFileSource.cpp \
    thirdparty/live/liveMedia/FramedFilter.cpp \
    thirdparty/live/liveMedia/FramedSource.cpp \
    thirdparty/live/liveMedia/GenericMediaServer.cpp \
    thirdparty/live/liveMedia/GSMAudioRTPSink.cpp \
    thirdparty/live/liveMedia/H261VideoRTPSource.cpp \
    thirdparty/live/liveMedia/H263plusVideoFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/H263plusVideoRTPSink.cpp \
    thirdparty/live/liveMedia/H263plusVideoRTPSource.cpp \
    thirdparty/live/liveMedia/H263plusVideoStreamFramer.cpp \
    thirdparty/live/liveMedia/H263plusVideoStreamParser.cpp \
    thirdparty/live/liveMedia/H264or5VideoFileSink.cpp \
    thirdparty/live/liveMedia/H264or5VideoRTPSink.cpp \
    thirdparty/live/liveMedia/H264or5VideoStreamDiscreteFramer.cpp \
    thirdparty/live/liveMedia/H264or5VideoStreamFramer.cpp \
    thirdparty/live/liveMedia/H264VideoFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/H264VideoFileSink.cpp \
    thirdparty/live/liveMedia/H264VideoRTPSink.cpp \
    thirdparty/live/liveMedia/H264VideoRTPSource.cpp \
    thirdparty/live/liveMedia/H264VideoStreamDiscreteFramer.cpp \
    thirdparty/live/liveMedia/H264VideoStreamFramer.cpp \
    thirdparty/live/liveMedia/H265VideoFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/H265VideoFileSink.cpp \
    thirdparty/live/liveMedia/H265VideoRTPSink.cpp \
    thirdparty/live/liveMedia/H265VideoRTPSource.cpp \
    thirdparty/live/liveMedia/H265VideoStreamDiscreteFramer.cpp \
    thirdparty/live/liveMedia/H265VideoStreamFramer.cpp \
    thirdparty/live/liveMedia/InputFile.cpp \
    thirdparty/live/liveMedia/JPEGVideoRTPSink.cpp \
    thirdparty/live/liveMedia/JPEGVideoRTPSource.cpp \
    thirdparty/live/liveMedia/JPEGVideoSource.cpp \
    thirdparty/live/liveMedia/Locale.cpp \
    thirdparty/live/liveMedia/MatroskaDemuxedTrack.cpp \
    thirdparty/live/liveMedia/MatroskaFile.cpp \
    thirdparty/live/liveMedia/MatroskaFileParser.cpp \
    thirdparty/live/liveMedia/MatroskaFileServerDemux.cpp \
    thirdparty/live/liveMedia/MatroskaFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/Media.cpp \
    thirdparty/live/liveMedia/MediaSession.cpp \
    thirdparty/live/liveMedia/MediaSink.cpp \
    thirdparty/live/liveMedia/MediaSource.cpp \
    thirdparty/live/liveMedia/MP3ADU.cpp \
    thirdparty/live/liveMedia/MP3ADUdescriptor.cpp \
    thirdparty/live/liveMedia/MP3ADUinterleaving.cpp \
    thirdparty/live/liveMedia/MP3ADURTPSink.cpp \
    thirdparty/live/liveMedia/MP3ADURTPSource.cpp \
    thirdparty/live/liveMedia/MP3ADUTranscoder.cpp \
    thirdparty/live/liveMedia/MP3AudioFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/MP3AudioMatroskaFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/MP3FileSource.cpp \
    thirdparty/live/liveMedia/MP3Internals.cpp \
    thirdparty/live/liveMedia/MP3InternalsHuffman.cpp \
    thirdparty/live/liveMedia/MP3InternalsHuffmanTable.cpp \
    thirdparty/live/liveMedia/MP3StreamState.cpp \
    thirdparty/live/liveMedia/MP3Transcoder.cpp \
    thirdparty/live/liveMedia/MPEG1or2AudioRTPSink.cpp \
    thirdparty/live/liveMedia/MPEG1or2AudioRTPSource.cpp \
    thirdparty/live/liveMedia/MPEG1or2AudioStreamFramer.cpp \
    thirdparty/live/liveMedia/MPEG1or2Demux.cpp \
    thirdparty/live/liveMedia/MPEG1or2DemuxedElementaryStream.cpp \
    thirdparty/live/liveMedia/MPEG1or2DemuxedServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/MPEG1or2FileServerDemux.cpp \
    thirdparty/live/liveMedia/MPEG1or2VideoFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/MPEG1or2VideoRTPSink.cpp \
    thirdparty/live/liveMedia/MPEG1or2VideoRTPSource.cpp \
    thirdparty/live/liveMedia/MPEG1or2VideoStreamDiscreteFramer.cpp \
    thirdparty/live/liveMedia/MPEG1or2VideoStreamFramer.cpp \
    thirdparty/live/liveMedia/MPEG2IndexFromTransportStream.cpp \
    thirdparty/live/liveMedia/MPEG2TransportFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/MPEG2TransportStreamFramer.cpp \
    thirdparty/live/liveMedia/MPEG2TransportStreamFromESSource.cpp \
    thirdparty/live/liveMedia/MPEG2TransportStreamFromPESSource.cpp \
    thirdparty/live/liveMedia/MPEG2TransportStreamIndexFile.cpp \
    thirdparty/live/liveMedia/MPEG2TransportStreamMultiplexor.cpp \
    thirdparty/live/liveMedia/MPEG2TransportStreamTrickModeFilter.cpp \
    thirdparty/live/liveMedia/MPEG2TransportUDPServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/MPEG4ESVideoRTPSink.cpp \
    thirdparty/live/liveMedia/MPEG4ESVideoRTPSource.cpp \
    thirdparty/live/liveMedia/MPEG4GenericRTPSink.cpp \
    thirdparty/live/liveMedia/MPEG4GenericRTPSource.cpp \
    thirdparty/live/liveMedia/MPEG4LATMAudioRTPSink.cpp \
    thirdparty/live/liveMedia/MPEG4LATMAudioRTPSource.cpp \
    thirdparty/live/liveMedia/MPEG4VideoFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/MPEG4VideoStreamDiscreteFramer.cpp \
    thirdparty/live/liveMedia/MPEG4VideoStreamFramer.cpp \
    thirdparty/live/liveMedia/MPEGVideoStreamFramer.cpp \
    thirdparty/live/liveMedia/MPEGVideoStreamParser.cpp \
    thirdparty/live/liveMedia/MultiFramedRTPSink.cpp \
    thirdparty/live/liveMedia/MultiFramedRTPSource.cpp \
    thirdparty/live/liveMedia/OggDemuxedTrack.cpp \
    thirdparty/live/liveMedia/OggFile.cpp \
    thirdparty/live/liveMedia/OggFileParser.cpp \
    thirdparty/live/liveMedia/OggFileServerDemux.cpp \
    thirdparty/live/liveMedia/OggFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/OggFileSink.cpp \
    thirdparty/live/liveMedia/OnDemandServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/ourMD5.cpp \
    thirdparty/live/liveMedia/OutputFile.cpp \
    thirdparty/live/liveMedia/PassiveServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/ProxyServerMediaSession.cpp \
    thirdparty/live/liveMedia/QCELPAudioRTPSource.cpp \
    thirdparty/live/liveMedia/QuickTimeFileSink.cpp \
    thirdparty/live/liveMedia/QuickTimeGenericRTPSource.cpp \
    thirdparty/live/liveMedia/RTCP.cpp \
    thirdparty/live/liveMedia/RTPInterface.cpp \
    thirdparty/live/liveMedia/RTPSink.cpp \
    thirdparty/live/liveMedia/RTPSource.cpp \
    thirdparty/live/liveMedia/RTSPClient.cpp \
    thirdparty/live/liveMedia/RTSPCommon.cpp \
    thirdparty/live/liveMedia/RTSPRegisterSender.cpp \
    thirdparty/live/liveMedia/RTSPServer.cpp \
    thirdparty/live/liveMedia/RTSPServerSupportingHTTPStreaming.cpp \
    thirdparty/live/liveMedia/ServerMediaSession.cpp \
    thirdparty/live/liveMedia/SimpleRTPSink.cpp \
    thirdparty/live/liveMedia/SimpleRTPSource.cpp \
    thirdparty/live/liveMedia/SIPClient.cpp \
    thirdparty/live/liveMedia/StreamParser.cpp \
    thirdparty/live/liveMedia/StreamReplicator.cpp \
    thirdparty/live/liveMedia/T140TextRTPSink.cpp \
    thirdparty/live/liveMedia/TCPStreamSink.cpp \
    thirdparty/live/liveMedia/TextRTPSink.cpp \
    thirdparty/live/liveMedia/TheoraVideoRTPSink.cpp \
    thirdparty/live/liveMedia/TheoraVideoRTPSource.cpp \
    thirdparty/live/liveMedia/uLawAudioFilter.cpp \
    thirdparty/live/liveMedia/VideoRTPSink.cpp \
    thirdparty/live/liveMedia/VorbisAudioRTPSink.cpp \
    thirdparty/live/liveMedia/VorbisAudioRTPSource.cpp \
    thirdparty/live/liveMedia/VP8VideoRTPSink.cpp \
    thirdparty/live/liveMedia/VP8VideoRTPSource.cpp \
    thirdparty/live/liveMedia/VP9VideoRTPSink.cpp \
    thirdparty/live/liveMedia/VP9VideoRTPSource.cpp \
    thirdparty/live/liveMedia/WAVAudioFileServerMediaSubsession.cpp \
    thirdparty/live/liveMedia/WAVAudioFileSource.cpp \
    thirdparty/live/UsageEnvironment/HashTable.cpp \
    thirdparty/live/UsageEnvironment/strDup.cpp \
    thirdparty/live/UsageEnvironment/UsageEnvironment.cpp \
    DynamicRTSPServer.cpp \
    live555MediaServer.cpp \
    thirdparty/live/groupsock/inet.c \
    thirdparty/live/liveMedia/rtcp_from_spec.c

HEADERS += \
    thirdparty/live/BasicUsageEnvironment/include/BasicHashTable.hh \
    thirdparty/live/BasicUsageEnvironment/include/BasicUsageEnvironment.hh \
    thirdparty/live/BasicUsageEnvironment/include/BasicUsageEnvironment0.hh \
    thirdparty/live/BasicUsageEnvironment/include/BasicUsageEnvironment_version.hh \
    thirdparty/live/BasicUsageEnvironment/include/DelayQueue.hh \
    thirdparty/live/BasicUsageEnvironment/include/HandlerSet.hh \
    thirdparty/live/groupsock/include/GroupEId.hh \
    thirdparty/live/groupsock/include/Groupsock.hh \
    thirdparty/live/groupsock/include/groupsock_version.hh \
    thirdparty/live/groupsock/include/GroupsockHelper.hh \
    thirdparty/live/groupsock/include/IOHandlers.hh \
    thirdparty/live/groupsock/include/NetAddress.hh \
    thirdparty/live/groupsock/include/NetCommon.h \
    thirdparty/live/groupsock/include/NetInterface.hh \
    thirdparty/live/groupsock/include/TunnelEncaps.hh \
    thirdparty/live/liveMedia/include/AC3AudioFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/AC3AudioRTPSink.hh \
    thirdparty/live/liveMedia/include/AC3AudioRTPSource.hh \
    thirdparty/live/liveMedia/include/AC3AudioStreamFramer.hh \
    thirdparty/live/liveMedia/include/ADTSAudioFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/ADTSAudioFileSource.hh \
    thirdparty/live/liveMedia/include/AMRAudioFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/AMRAudioFileSink.hh \
    thirdparty/live/liveMedia/include/AMRAudioFileSource.hh \
    thirdparty/live/liveMedia/include/AMRAudioRTPSink.hh \
    thirdparty/live/liveMedia/include/AMRAudioRTPSource.hh \
    thirdparty/live/liveMedia/include/AMRAudioSource.hh \
    thirdparty/live/liveMedia/include/AudioInputDevice.hh \
    thirdparty/live/liveMedia/include/AudioRTPSink.hh \
    thirdparty/live/liveMedia/include/AVIFileSink.hh \
    thirdparty/live/liveMedia/include/Base64.hh \
    thirdparty/live/liveMedia/include/BasicUDPSink.hh \
    thirdparty/live/liveMedia/include/BasicUDPSource.hh \
    thirdparty/live/liveMedia/include/BitVector.hh \
    thirdparty/live/liveMedia/include/ByteStreamFileSource.hh \
    thirdparty/live/liveMedia/include/ByteStreamMemoryBufferSource.hh \
    thirdparty/live/liveMedia/include/ByteStreamMultiFileSource.hh \
    thirdparty/live/liveMedia/include/DeviceSource.hh \
    thirdparty/live/liveMedia/include/DigestAuthentication.hh \
    thirdparty/live/liveMedia/include/DVVideoFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/DVVideoRTPSink.hh \
    thirdparty/live/liveMedia/include/DVVideoRTPSource.hh \
    thirdparty/live/liveMedia/include/DVVideoStreamFramer.hh \
    thirdparty/live/liveMedia/include/FileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/FileSink.hh \
    thirdparty/live/liveMedia/include/FramedFileSource.hh \
    thirdparty/live/liveMedia/include/FramedFilter.hh \
    thirdparty/live/liveMedia/include/FramedSource.hh \
    thirdparty/live/liveMedia/include/GenericMediaServer.hh \
    thirdparty/live/liveMedia/include/GSMAudioRTPSink.hh \
    thirdparty/live/liveMedia/include/H261VideoRTPSource.hh \
    thirdparty/live/liveMedia/include/H263plusVideoFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/H263plusVideoRTPSink.hh \
    thirdparty/live/liveMedia/include/H263plusVideoRTPSource.hh \
    thirdparty/live/liveMedia/include/H263plusVideoStreamFramer.hh \
    thirdparty/live/liveMedia/include/H264or5VideoFileSink.hh \
    thirdparty/live/liveMedia/include/H264or5VideoRTPSink.hh \
    thirdparty/live/liveMedia/include/H264or5VideoStreamDiscreteFramer.hh \
    thirdparty/live/liveMedia/include/H264or5VideoStreamFramer.hh \
    thirdparty/live/liveMedia/include/H264VideoFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/H264VideoFileSink.hh \
    thirdparty/live/liveMedia/include/H264VideoRTPSink.hh \
    thirdparty/live/liveMedia/include/H264VideoRTPSource.hh \
    thirdparty/live/liveMedia/include/H264VideoStreamDiscreteFramer.hh \
    thirdparty/live/liveMedia/include/H264VideoStreamFramer.hh \
    thirdparty/live/liveMedia/include/H265VideoFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/H265VideoFileSink.hh \
    thirdparty/live/liveMedia/include/H265VideoRTPSink.hh \
    thirdparty/live/liveMedia/include/H265VideoRTPSource.hh \
    thirdparty/live/liveMedia/include/H265VideoStreamDiscreteFramer.hh \
    thirdparty/live/liveMedia/include/H265VideoStreamFramer.hh \
    thirdparty/live/liveMedia/include/InputFile.hh \
    thirdparty/live/liveMedia/include/JPEGVideoRTPSink.hh \
    thirdparty/live/liveMedia/include/JPEGVideoRTPSource.hh \
    thirdparty/live/liveMedia/include/JPEGVideoSource.hh \
    thirdparty/live/liveMedia/include/liveMedia.hh \
    thirdparty/live/liveMedia/include/liveMedia_version.hh \
    thirdparty/live/liveMedia/include/Locale.hh \
    thirdparty/live/liveMedia/include/MatroskaFile.hh \
    thirdparty/live/liveMedia/include/MatroskaFileServerDemux.hh \
    thirdparty/live/liveMedia/include/Media.hh \
    thirdparty/live/liveMedia/include/MediaSession.hh \
    thirdparty/live/liveMedia/include/MediaSink.hh \
    thirdparty/live/liveMedia/include/MediaSource.hh \
    thirdparty/live/liveMedia/include/MediaTranscodingTable.hh \
    thirdparty/live/liveMedia/include/MP3ADU.hh \
    thirdparty/live/liveMedia/include/MP3ADUinterleaving.hh \
    thirdparty/live/liveMedia/include/MP3ADURTPSink.hh \
    thirdparty/live/liveMedia/include/MP3ADURTPSource.hh \
    thirdparty/live/liveMedia/include/MP3ADUTranscoder.hh \
    thirdparty/live/liveMedia/include/MP3AudioFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/MP3FileSource.hh \
    thirdparty/live/liveMedia/include/MP3Transcoder.hh \
    thirdparty/live/liveMedia/include/MPEG1or2AudioRTPSink.hh \
    thirdparty/live/liveMedia/include/MPEG1or2AudioRTPSource.hh \
    thirdparty/live/liveMedia/include/MPEG1or2AudioStreamFramer.hh \
    thirdparty/live/liveMedia/include/MPEG1or2Demux.hh \
    thirdparty/live/liveMedia/include/MPEG1or2DemuxedElementaryStream.hh \
    thirdparty/live/liveMedia/include/MPEG1or2DemuxedServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/MPEG1or2FileServerDemux.hh \
    thirdparty/live/liveMedia/include/MPEG1or2VideoFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/MPEG1or2VideoRTPSink.hh \
    thirdparty/live/liveMedia/include/MPEG1or2VideoRTPSource.hh \
    thirdparty/live/liveMedia/include/MPEG1or2VideoStreamDiscreteFramer.hh \
    thirdparty/live/liveMedia/include/MPEG1or2VideoStreamFramer.hh \
    thirdparty/live/liveMedia/include/MPEG2IndexFromTransportStream.hh \
    thirdparty/live/liveMedia/include/MPEG2TransportFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/MPEG2TransportStreamFramer.hh \
    thirdparty/live/liveMedia/include/MPEG2TransportStreamFromESSource.hh \
    thirdparty/live/liveMedia/include/MPEG2TransportStreamFromPESSource.hh \
    thirdparty/live/liveMedia/include/MPEG2TransportStreamIndexFile.hh \
    thirdparty/live/liveMedia/include/MPEG2TransportStreamMultiplexor.hh \
    thirdparty/live/liveMedia/include/MPEG2TransportStreamTrickModeFilter.hh \
    thirdparty/live/liveMedia/include/MPEG2TransportUDPServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/MPEG4ESVideoRTPSink.hh \
    thirdparty/live/liveMedia/include/MPEG4ESVideoRTPSource.hh \
    thirdparty/live/liveMedia/include/MPEG4GenericRTPSink.hh \
    thirdparty/live/liveMedia/include/MPEG4GenericRTPSource.hh \
    thirdparty/live/liveMedia/include/MPEG4LATMAudioRTPSink.hh \
    thirdparty/live/liveMedia/include/MPEG4LATMAudioRTPSource.hh \
    thirdparty/live/liveMedia/include/MPEG4VideoFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/MPEG4VideoStreamDiscreteFramer.hh \
    thirdparty/live/liveMedia/include/MPEG4VideoStreamFramer.hh \
    thirdparty/live/liveMedia/include/MPEGVideoStreamFramer.hh \
    thirdparty/live/liveMedia/include/MultiFramedRTPSink.hh \
    thirdparty/live/liveMedia/include/MultiFramedRTPSource.hh \
    thirdparty/live/liveMedia/include/OggFile.hh \
    thirdparty/live/liveMedia/include/OggFileServerDemux.hh \
    thirdparty/live/liveMedia/include/OggFileSink.hh \
    thirdparty/live/liveMedia/include/OnDemandServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/ourMD5.hh \
    thirdparty/live/liveMedia/include/OutputFile.hh \
    thirdparty/live/liveMedia/include/PassiveServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/ProxyServerMediaSession.hh \
    thirdparty/live/liveMedia/include/QCELPAudioRTPSource.hh \
    thirdparty/live/liveMedia/include/QuickTimeFileSink.hh \
    thirdparty/live/liveMedia/include/QuickTimeGenericRTPSource.hh \
    thirdparty/live/liveMedia/include/RTCP.hh \
    thirdparty/live/liveMedia/include/RTPInterface.hh \
    thirdparty/live/liveMedia/include/RTPSink.hh \
    thirdparty/live/liveMedia/include/RTPSource.hh \
    thirdparty/live/liveMedia/include/RTSPClient.hh \
    thirdparty/live/liveMedia/include/RTSPCommon.hh \
    thirdparty/live/liveMedia/include/RTSPRegisterSender.hh \
    thirdparty/live/liveMedia/include/RTSPServer.hh \
    thirdparty/live/liveMedia/include/RTSPServerSupportingHTTPStreaming.hh \
    thirdparty/live/liveMedia/include/ServerMediaSession.hh \
    thirdparty/live/liveMedia/include/SimpleRTPSink.hh \
    thirdparty/live/liveMedia/include/SimpleRTPSource.hh \
    thirdparty/live/liveMedia/include/SIPClient.hh \
    thirdparty/live/liveMedia/include/StreamReplicator.hh \
    thirdparty/live/liveMedia/include/T140TextRTPSink.hh \
    thirdparty/live/liveMedia/include/TCPStreamSink.hh \
    thirdparty/live/liveMedia/include/TextRTPSink.hh \
    thirdparty/live/liveMedia/include/TheoraVideoRTPSink.hh \
    thirdparty/live/liveMedia/include/TheoraVideoRTPSource.hh \
    thirdparty/live/liveMedia/include/uLawAudioFilter.hh \
    thirdparty/live/liveMedia/include/VideoRTPSink.hh \
    thirdparty/live/liveMedia/include/VorbisAudioRTPSink.hh \
    thirdparty/live/liveMedia/include/VorbisAudioRTPSource.hh \
    thirdparty/live/liveMedia/include/VP8VideoRTPSink.hh \
    thirdparty/live/liveMedia/include/VP8VideoRTPSource.hh \
    thirdparty/live/liveMedia/include/VP9VideoRTPSink.hh \
    thirdparty/live/liveMedia/include/VP9VideoRTPSource.hh \
    thirdparty/live/liveMedia/include/WAVAudioFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/include/WAVAudioFileSource.hh \
    thirdparty/live/liveMedia/EBMLNumber.hh \
    thirdparty/live/liveMedia/H263plusVideoStreamParser.hh \
    thirdparty/live/liveMedia/MatroskaDemuxedTrack.hh \
    thirdparty/live/liveMedia/MatroskaFileParser.hh \
    thirdparty/live/liveMedia/MatroskaFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/MP3ADUdescriptor.hh \
    thirdparty/live/liveMedia/MP3AudioMatroskaFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/MP3Internals.hh \
    thirdparty/live/liveMedia/MP3InternalsHuffman.hh \
    thirdparty/live/liveMedia/MP3StreamState.hh \
    thirdparty/live/liveMedia/MPEGVideoStreamParser.hh \
    thirdparty/live/liveMedia/OggDemuxedTrack.hh \
    thirdparty/live/liveMedia/OggFileParser.hh \
    thirdparty/live/liveMedia/OggFileServerMediaSubsession.hh \
    thirdparty/live/liveMedia/rtcp_from_spec.h \
    thirdparty/live/liveMedia/StreamParser.hh \
    thirdparty/live/UsageEnvironment/include/Boolean.hh \
    thirdparty/live/UsageEnvironment/include/HashTable.hh \
    thirdparty/live/UsageEnvironment/include/strDup.hh \
    thirdparty/live/UsageEnvironment/include/UsageEnvironment.hh \
    thirdparty/live/UsageEnvironment/include/UsageEnvironment_version.hh \
    DynamicRTSPServer.hh \
    version.hh
